/* scRNA-seq 互動式考題 — 題庫資料（中英雙語版）
 * Bilingual question bank.
 * 題型 type: "single" 單選 | "multi" 多選 | "tf" 是非
 * 單選 ans: "A"|"B"|"C"|"D"
 * 多選 ans: ["A","C"]
 * 是非 ans: "T"|"F"
 * 中英對照：stem/A/B/C/D/exp 為中文；stem_en/A_en/B_en/C_en/D_en/exp_en 為英文
 */
window.QUIZ_DATA = {
  scrna: {
    label: "scRNA-seq 互動考題",
    label_en: "scRNA-seq Interactive Quiz",
    labels_en: {
      "核心分析流程": "Core Analysis Pipeline",
      "進階分析主題": "Advanced Topics",
      "Step 1：品質管控 (QC)": "Step 1: Quality Control (QC)",
      "Step 2：標準化 (Normalization)": "Step 2: Normalization",
      "Step 3：高變異基因 (HVGs)": "Step 3: Variable Features (HVGs)",
      "Step 4：縮放 (Scaling)": "Step 4: Scaling",
      "Step 5：主成分分析 (PCA)": "Step 5: PCA",
      "Step 6：聚類 (Clustering)": "Step 6: Clustering",
      "Step 7：UMAP 視覺化": "Step 7: UMAP Visualization",
      "Step 8：細胞註釋 (Annotation)": "Step 8: Cell Annotation",
      "Step 9：差異表達分析 (DE)": "Step 9: Differential Expression (DE)",
      "Advanced：資料整合 (Integration)": "Advanced: Data Integration",
      "Advanced：細胞通訊 (CellChat)": "Advanced: Cell-Cell Communication",
      "Advanced：軌跡分析 (Trajectory)": "Advanced: Trajectory / Pseudotime"
    },
    subjects: {
      "核心分析流程": {
        "Step 1：品質管控 (QC)": [
          { type:"single",
            stem:"在 scRNA-seq 數據中，percent.mt（粒線體基因比例）過高，最常見的解讀為何？",
            stem_en:"In scRNA-seq data, what does an excessively high percent.mt (mitochondrial gene fraction) most commonly indicate?",
            A:"細胞處於高度活躍的轉錄狀態", A_en:"The cell is in a highly active transcriptional state",
            B:"細胞可能死亡或瀕死，胞質 mRNA 已流失", B_en:"The cell is likely dead or dying with cytoplasmic mRNA lost",
            C:"細胞為雙細胞 (doublet)", C_en:"The cell is a doublet",
            D:"代表稀有亞群，需特別保留", D_en:"It represents a rare subpopulation worth keeping",
            ans:"B",
            exp:"細胞破裂時胞質 mRNA 外漏，但粒線體因雙層膜保留 RNA，使 MT% 比例上升，是判斷細胞死活的關鍵指標。",
            exp_en:"When a cell ruptures, cytoplasmic mRNA leaks out while mitochondrial RNA is retained by the double membrane. Elevated MT% therefore signals dying cells — a key viability metric." },
          { type:"single",
            stem:"某細胞同時擁有極高的 nFeature_RNA 與極高的 nCount_RNA，最可能的原因是？",
            stem_en:"A cell shows extremely high nFeature_RNA AND extremely high nCount_RNA. The most likely cause is?",
            A:"該細胞轉錄極為旺盛", A_en:"The cell is exceptionally transcriptionally active",
            B:"定序深度比較深的正常細胞", B_en:"A normal cell that happened to be deeply sequenced",
            C:"極可能是 doublet（兩個細胞同入一個液滴）", C_en:"Most likely a doublet (two cells in one droplet)",
            D:"屬於罕見靜止期細胞", D_en:"A rare quiescent cell",
            ans:"C",
            exp:"兩個細胞合併在同一液滴中，會使基因數與 UMI 數同時異常偏高，這是 doublet 的典型特徵。",
            exp_en:"Two cells co-encapsulated in one droplet inflate both gene count and UMI count simultaneously — a hallmark of doublets." },
          { type:"single",
            stem:"有關 nFeature_RNA 過低（如 < 200）的解釋，下列何者最合理？",
            stem_en:"Which is the most reasonable explanation for an extremely low nFeature_RNA (e.g., < 200)?",
            A:"屬於極度活躍的細胞", A_en:"An extremely active cell",
            B:"代表細胞破裂或為空液滴，僅捕獲少量環境 RNA", B_en:"Cell rupture or empty droplet — only ambient RNA captured",
            C:"代表 doublet", C_en:"A doublet",
            D:"代表正常 T 細胞", D_en:"A normal T cell",
            ans:"B",
            exp:"極低基因數通常代表細胞破裂、空液滴或品質極差，僅含少量 ambient RNA。",
            exp_en:"Very low gene count usually means cell rupture, empty droplet, or extremely low quality with only ambient RNA." },
          { type:"multi",
            stem:"下列哪些屬於常見的「進階 QC」步驟？（多選）",
            stem_en:"Which of the following are common 'advanced QC' steps? (Multiple)",
            A:"Doublet 偵測（DoubletFinder/Scrublet）", A_en:"Doublet detection (DoubletFinder/Scrublet)",
            B:"環境 RNA 移除（SoupX/CellBender）", B_en:"Ambient RNA removal (SoupX/CellBender)",
            C:"使用 PCA 降維", C_en:"PCA dimensionality reduction",
            D:"基因層級過濾（min.cells = 3）", D_en:"Gene-level filtering (min.cells = 3)",
            ans:["A","B","D"],
            exp:"A、B、D 都是 QC 範疇；PCA 屬於下游降維步驟，不在 QC 過濾中。",
            exp_en:"A, B, and D belong to QC; PCA is a downstream dimensionality reduction step, not part of QC filtering." },
          { type:"tf",
            stem:"是非題：所有 scRNA-seq 樣本都應該套用「MT% < 5%」這個放諸四海皆準的閾值。",
            stem_en:"True/False: All scRNA-seq samples should apply the universal threshold of 'MT% < 5%'.",
            ans:"F",
            exp:"沒有通用閾值。心肌、肝、肌肉等組織粒線體基線天然偏高，需依組織與物種調整。",
            exp_en:"There is no universal threshold. Tissues like cardiomyocytes, liver, and muscle have naturally high mitochondrial baselines — adjust per tissue and species." },
          { type:"single",
            stem:"關於 doublet 偵測，下列敘述何者正確？",
            stem_en:"Which statement about doublet detection is correct?",
            A:"設定 nFeature 上限即可移除全部 doublets", A_en:"Setting an nFeature ceiling removes all doublets",
            B:"必須結合演算法（如 DoubletFinder/Scrublet）模擬並計算 doublet score", B_en:"Specialized algorithms (DoubletFinder/Scrublet) are needed to simulate and score doublets",
            C:"Doublets 只存在 Smart-seq 平台", C_en:"Doublets only occur on Smart-seq platforms",
            D:"Doublets 不影響下游分析", D_en:"Doublets do not affect downstream analysis",
            ans:"B",
            exp:"由兩個小細胞組成的 doublet 指標可能僅略高於正常細胞，需要演算法模擬合併表達譜並計算 score。",
            exp_en:"Doublets formed from two small cells may be only marginally above normal — algorithms simulate merged profiles and compute a score." },
          { type:"single",
            stem:"環境 RNA（Ambient RNA / soup）會造成什麼問題？",
            stem_en:"What problem does ambient RNA (soup) cause?",
            A:"只影響統計計算速度", A_en:"It only affects computation speed",
            B:"使原本不該表現某基因的細胞錯誤偵測到該基因，造成污染", B_en:"It causes contamination — cells appear to express genes they shouldn't",
            C:"使 PCA 主成分數變多", C_en:"It increases the number of PCA components",
            D:"完全不影響下游聚類結果", D_en:"It does not affect downstream clustering at all",
            ans:"B",
            exp:"破裂細胞釋出的 RNA 會被一同包進液滴，例如 T 細胞被偵測到肝特異基因 ALB，需以 SoupX/CellBender 校正。",
            exp_en:"Lysed cells release RNA that gets co-encapsulated, e.g., T cells appearing to express liver-specific ALB. Corrected by SoupX/CellBender." },
          { type:"multi",
            stem:"下列哪些工具是用於 doublet 偵測的？（多選）",
            stem_en:"Which of the following tools are used for doublet detection? (Multiple)",
            A:"DoubletFinder", A_en:"DoubletFinder",
            B:"Scrublet", B_en:"Scrublet",
            C:"SoupX", C_en:"SoupX",
            D:"scDblFinder", D_en:"scDblFinder",
            ans:["A","B","D"],
            exp:"SoupX 是處理 ambient RNA 的工具，不屬於 doublet 偵測。",
            exp_en:"SoupX is for ambient RNA, not doublet detection." },
          { type:"tf",
            stem:"是非題：自適應閾值（如中位數 ± 3 × MAD）在多樣本整合分析時通常優於固定閾值。",
            stem_en:"True/False: Adaptive thresholds (e.g., median ± 3 × MAD) are usually better than fixed thresholds in multi-sample integration analysis.",
            ans:"T",
            exp:"多批次資料各自分佈不同，自適應 MAD-based 方法能讓每個樣本依其分佈決定閾值，更穩健。",
            exp_en:"Multi-batch data have different distributions; MAD-based adaptive thresholds let each sample set its own thresholds, which is more robust." },
          { type:"single",
            stem:"基因層級的 QC 中，常用的「min.cells = 3」目的為何？",
            stem_en:"In gene-level QC, what is the purpose of 'min.cells = 3'?",
            A:"剔除可能為定序錯誤、僅在極少細胞表現的低品質基因", A_en:"Remove possibly artefactual genes that show up in too few cells",
            B:"剔除高度表達的看家基因", B_en:"Remove highly expressed housekeeping genes",
            C:"加速降維", C_en:"Speed up dimensionality reduction",
            D:"挑選高變異基因", D_en:"Select highly variable genes",
            ans:"A",
            exp:"極少細胞中出現的基因多為定序假象或表現量過低無法提供統計顯著性，習慣上會過濾。",
            exp_en:"Genes detected in too few cells are likely sequencing artifacts or too lowly expressed for statistical power, so they are routinely filtered." },
          { type:"single",
            stem:"為什麼建議「先看圖再設閾值」（VlnPlot / 散佈圖）？",
            stem_en:"Why is it recommended to 'visualize first, then set thresholds' (VlnPlot / scatter)?",
            A:"只是為了製圖好看", A_en:"Just to make the plot look nice",
            B:"小提琴圖與散佈圖能反映實際資料分佈，避免主觀數字過嚴或過寬", B_en:"Violin and scatter plots reflect the actual data distribution, avoiding subjective thresholds that are too strict or too lax",
            C:"一定要做才符合論文格式", C_en:"It is required for paper formatting",
            D:"為了符合 Seurat 的版本更新", D_en:"To comply with Seurat version updates",
            ans:"B",
            exp:"QC 是高度資料相關的步驟，視覺化能讓使用者根據真實分佈決定合理閾值。",
            exp_en:"QC is highly data-dependent; visualization lets you set sensible thresholds based on the real distribution." },
          { type:"multi",
            stem:"下列哪些情況可能讓你「寧可寬鬆」設定 QC 閾值？（多選）",
            stem_en:"Which situations argue for 'lenient' QC thresholds? (Multiple)",
            A:"關注稀有細胞亞群", A_en:"Focus on rare cell subpopulations",
            B:"想保留靜止期或小型細胞", B_en:"Want to retain quiescent or small cells",
            C:"純粹追求最高的細胞數", C_en:"Pure pursuit of highest possible cell count",
            D:"組織背景已知有特殊 MT% 特徵", D_en:"The tissue is known to have unusual MT% characteristics",
            ans:["A","B","D"],
            exp:"C 為純數量導向，不是合理動機；A、B、D 都是過嚴閾值可能誤殺真實族群的情境。",
            exp_en:"C is pure quantity chasing, not a valid reason. A/B/D all describe situations where strict thresholds may erroneously remove real populations." }
        ],
        "Step 2：標準化 (Normalization)": [
          { type:"single",
            stem:"Normalization 主要解決下列哪一類問題？",
            stem_en:"What kind of problem does Normalization mainly address?",
            A:"批次效應", A_en:"Batch effects",
            B:"細胞間的技術性差異（測序深度、捕獲效率等）造成的 read counts 差異", B_en:"Inter-cell technical differences (sequencing depth, capture efficiency, etc.) causing read count variation",
            C:"基因功能注釋", C_en:"Gene function annotation",
            D:"細胞類型命名", D_en:"Cell type naming",
            ans:"B",
            exp:"Normalization 校正的是技術性偏差，使不同細胞的表現量可以比較。",
            exp_en:"Normalization corrects technical biases so that expression values across cells become comparable." },
          { type:"single",
            stem:"Seurat 預設 LogNormalize 的核心邏輯為何？",
            stem_en:"What is the core logic of Seurat's default LogNormalize?",
            A:"先除以細胞總 counts × 10000，再取自然對數 ln(x+1)", A_en:"Divide by total counts per cell, multiply by 10000, then take ln(x+1)",
            B:"取 Z-score 標準化", B_en:"Apply Z-score standardization",
            C:"基於負二項分佈建模", C_en:"Model with a negative binomial distribution",
            D:"使用 PCA 降維", D_en:"Use PCA for dimensionality reduction",
            ans:"A",
            exp:"LogNormalize：每細胞除以總 count、乘以 scale factor 10000，最後 ln(x+1)。",
            exp_en:"LogNormalize: divide by total count per cell, multiply by scale factor 10000, then ln(x+1)." },
          { type:"single",
            stem:"關於 SCTransform，下列敘述何者正確？",
            stem_en:"Which statement about SCTransform is correct?",
            A:"是基於正則化負二項回歸（Regularized NB）建模殘差的方法", A_en:"It models residuals via regularized negative binomial regression",
            B:"只是簡單的對數轉換", B_en:"It is just a simple log transform",
            C:"完全不需 normalization，直接用於 PCA", C_en:"It bypasses normalization and feeds directly into PCA",
            D:"與 LogNormalize 完全相同", D_en:"Identical to LogNormalize",
            ans:"A",
            exp:"SCTransform 對 scRNA-seq 高度稀疏資料建立負二項回歸並輸出 Pearson 殘差，目前為 Seurat 主流推薦。",
            exp_en:"SCTransform fits a negative binomial regression to sparse scRNA-seq data and outputs Pearson residuals — the current Seurat recommendation." },
          { type:"multi",
            stem:"下列哪些是 scRNA-seq 數據需要 normalization 的「技術原因」？（多選）",
            stem_en:"Which of these are 'technical reasons' scRNA-seq data needs normalization? (Multiple)",
            A:"定序深度（Sequencing Depth）差異", A_en:"Sequencing depth differences",
            B:"逆轉錄/文庫備製的捕獲效率差異", B_en:"Differences in reverse transcription / library prep capture efficiency",
            C:"細胞自身真實的基因表達差異", C_en:"True biological differences between cells",
            D:"液滴試劑量微小差異", D_en:"Minor reagent volume differences across droplets",
            ans:["A","B","D"],
            exp:"C 屬於真實生物學差異，不是要校正掉的對象；其餘為技術原因。",
            exp_en:"C is true biological variation, which we do NOT want to remove. The rest are technical reasons." },
          { type:"tf",
            stem:"是非題：Normalization 後的數值已經完全等同於每個細胞的真實表達量。",
            stem_en:"True/False: After normalization, values exactly equal each cell's true expression amount.",
            ans:"F",
            exp:"Normalization 校正了系統性技術差異，但稀疏性、捕獲偏差仍存在，數值是相對的而非絕對。",
            exp_en:"Normalization corrects systematic technical differences but sparsity and capture biases remain — values are relative, not absolute." },
          { type:"single",
            stem:"關於 Scran 解卷積（Pool-based deconvolution），最適合的場景是？",
            stem_en:"For which scenario is Scran pool-based deconvolution most suitable?",
            A:"細胞間 RNA 含量差異極大時", A_en:"When RNA content varies greatly between cells",
            B:"做 ChIP-seq 分析", B_en:"For ChIP-seq analysis",
            C:"做 bulk RNA-seq", C_en:"For bulk RNA-seq",
            D:"代替 PCA", D_en:"As a replacement for PCA",
            ans:"A",
            exp:"Scran 透過細胞池估算 size factor，特別適合 RNA 量差異大的情況（如混合不同尺寸細胞）。",
            exp_en:"Scran estimates size factors via cell pools, well-suited when RNA amounts differ greatly (e.g., mixed cell sizes)." },
          { type:"single",
            stem:"以下何者「不是」 normalization 處理的目標？",
            stem_en:"Which is NOT a target of normalization?",
            A:"消除細胞間定序深度差異", A_en:"Remove sequencing depth differences between cells",
            B:"統一不同細胞間的 RNA 捕獲效率落差", B_en:"Even out RNA capture efficiency differences",
            C:"消除批次效應 (batch effect)", C_en:"Remove batch effects",
            D:"使後續 PCA/聚類結果更可靠", D_en:"Make downstream PCA/clustering more reliable",
            ans:"C",
            exp:"批次效應屬於樣本層級系統性差異，需要 integration 步驟處理，不是 normalization 範疇。",
            exp_en:"Batch effects are sample-level systematic differences handled by integration, not normalization." },
          { type:"tf",
            stem:"是非題：Normalization 與 Scaling 在 scRNA-seq 中是同一件事。",
            stem_en:"True/False: In scRNA-seq, Normalization and Scaling are the same thing.",
            ans:"F",
            exp:"Normalization 校正細胞間總量差異；Scaling 是基因層級的 Z-score 處理，兩者目的不同。",
            exp_en:"Normalization corrects per-cell total differences; Scaling applies a per-gene Z-score — different purposes." },
          { type:"single",
            stem:"在「快速探索」與「正式分析」之間，目前較主流的選擇是？",
            stem_en:"Between 'quick exploration' and 'formal analysis', what is the current mainstream choice?",
            A:"任何分析都用 LogNormalize", A_en:"Use LogNormalize for everything",
            B:"快速探索可用 LogNormalize；正式分析常推薦 SCTransform 或 Scran", B_en:"LogNormalize for quick exploration; SCTransform or Scran often recommended for formal analysis",
            C:"完全不做 normalization", C_en:"Do not normalize at all",
            D:"都改用 bulk RNA-seq 演算法", D_en:"Switch to bulk RNA-seq algorithms",
            ans:"B",
            exp:"LogNormalize 速度快、適合探索；SCTransform/Scran 對稀疏與異質性處理更佳，常用於正式分析。",
            exp_en:"LogNormalize is fast and good for exploration; SCTransform/Scran handle sparsity and heterogeneity better for formal analysis." },
          { type:"multi",
            stem:"關於處理零值（zero counts），下列敘述何者正確？（多選）",
            stem_en:"Which statements about handling zeros (zero counts) are correct? (Multiple)",
            A:"LogNormalize 對大量零值處理一般，仍會留下噪音", A_en:"LogNormalize handles many zeros only adequately and leaves residual noise",
            B:"SCTransform 透過建模殘差，較能處理零膨脹", B_en:"SCTransform handles zero-inflation better via residual modeling",
            C:"Scran 在細胞池估算上比 LogNormalize 更穩健於高零比例", C_en:"Scran is more robust to high zero proportions via pooled estimation",
            D:"處理零值與標準化無關", D_en:"Handling zeros is unrelated to normalization",
            ans:["A","B","C"],
            exp:"D 錯誤；單細胞極端稀疏的零值正是現代 normalization 演算法主要要解決的問題之一。",
            exp_en:"D is wrong; the extreme sparsity of single-cell data is exactly what modern normalization algorithms must address." },
          { type:"single",
            stem:"當細胞間總體 RNA 含量本身具有真實生物學差異（例如靜止 vs 活躍）時，較合適的 normalization 策略為？",
            stem_en:"When cells truly differ biologically in total RNA content (e.g., quiescent vs active), which normalization strategy is more appropriate?",
            A:"完全跳過 normalization", A_en:"Skip normalization entirely",
            B:"使用具備穩健 size factor 的方法（如 Scran 解卷積）以避免抹平真實差異", B_en:"Use methods with robust size factors (e.g., Scran deconvolution) to avoid erasing real differences",
            C:"使用最大值標準化", C_en:"Use max-value normalization",
            D:"以中位數截斷", D_en:"Trim at the median",
            ans:"B",
            exp:"當生物變異與技術變異交織時，size factor 估計需更謹慎，Scran 的 pool-based 方法是經典解。",
            exp_en:"When biological and technical variation are intertwined, size factor estimation must be careful — Scran's pool-based approach is a classic solution." }
        ],
        "Step 3：高變異基因 (HVGs)": [
          { type:"single",
            stem:"為什麼不直接拿全部基因進入 PCA，而要先挑選 HVGs？",
            stem_en:"Why not feed all genes into PCA directly — why pre-select HVGs?",
            A:"全部基因運算量大且充滿低訊號雜訊基因，HVGs 能聚焦在最具區分力的特徵", A_en:"All genes are computationally heavy and noisy; HVGs focus on the most discriminative features",
            B:"PCA 不接受多基因", B_en:"PCA does not accept many genes",
            C:"基因數越少越科學", C_en:"Fewer genes is more scientific",
            D:"避免基因被重複計算", D_en:"To avoid double-counting genes",
            ans:"A",
            exp:"絕大多數基因表現變異很小（如管家基因），對細胞分群幫助有限，挑 HVGs 可降噪並加速。",
            exp_en:"Most genes (e.g., housekeeping) show little variation and contribute little to clustering. Selecting HVGs reduces noise and speeds up analysis." },
          { type:"single",
            stem:"以下哪一類基因最不可能被選為 HVG？",
            stem_en:"Which type of gene is LEAST likely to be selected as HVG?",
            A:"細胞類型特異 marker", A_en:"Cell type-specific markers",
            B:"細胞週期相關基因", B_en:"Cell cycle related genes",
            C:"管家基因（如 GAPDH）", C_en:"Housekeeping genes (e.g., GAPDH)",
            D:"分化相關轉錄因子", D_en:"Differentiation-related transcription factors",
            ans:"C",
            exp:"管家基因在細胞間表現平穩、變異小，通常不會被選為 HVG。",
            exp_en:"Housekeeping genes are stable across cells with low variance — typically not selected as HVGs." },
          { type:"single",
            stem:"Seurat v3+ 的 vst 方法選擇 HVGs 的核心邏輯為何？",
            stem_en:"What is the core logic of Seurat v3+'s vst method for HVG selection?",
            A:"挑選 mean 最高的基因", A_en:"Pick genes with the highest mean",
            B:"以 mean-variance 關係建模，挑選變異度高於預期的基因", B_en:"Model the mean-variance relationship, pick genes with variance above expectation",
            C:"挑選表達 = 0 的基因", C_en:"Pick genes with expression = 0",
            D:"挑選看家基因", D_en:"Pick housekeeping genes",
            ans:"B",
            exp:"vst 對 mean-variance 進行擬合，標準化變異後再挑選 top N 個變異最高的基因。",
            exp_en:"vst fits the mean-variance trend, normalizes variance, then picks the top N highest-variance genes." },
          { type:"tf",
            stem:"是非題：HVG 數量越多越好，所以建議全部基因都納入。",
            stem_en:"True/False: More HVGs is always better, so include all genes.",
            ans:"F",
            exp:"過多基因會引入雜訊；常見選 2000–3000 個。實務上需依資料規模與實驗目的調整。",
            exp_en:"Too many genes introduce noise; 2000–3000 is typical. Adjust based on data scale and goals." },
          { type:"multi",
            stem:"下列哪些是常見挑選 HVGs 的方法？（多選）",
            stem_en:"Which are common methods to select HVGs? (Multiple)",
            A:"Seurat 的 vst", A_en:"Seurat's vst",
            B:"Seurat 的 mean.var.plot (MVP)", B_en:"Seurat's mean.var.plot (MVP)",
            C:"Scanpy 的 highly_variable_genes (cell_ranger / seurat / seurat_v3)", C_en:"Scanpy's highly_variable_genes (cell_ranger / seurat / seurat_v3)",
            D:"Z-score 標準化", D_en:"Z-score standardization",
            ans:["A","B","C"],
            exp:"D 是 Scaling 步驟，不是 HVG 的挑選方法。",
            exp_en:"D is the Scaling step, not an HVG selection method." },
          { type:"single",
            stem:"通常推薦的 HVG 數量大約落在？",
            stem_en:"What is the commonly recommended number of HVGs?",
            A:"50–100 個", A_en:"50–100",
            B:"500–1000 個", B_en:"500–1000",
            C:"2000–3000 個（常見預設）", C_en:"2000–3000 (common default)",
            D:"全部基因", D_en:"All genes",
            ans:"C",
            exp:"Seurat 預設 nfeatures=2000；Scanpy 多以 ~2000–3000 為合理上限。",
            exp_en:"Seurat default nfeatures=2000; Scanpy commonly uses ~2000–3000 as a reasonable upper bound." },
          { type:"single",
            stem:"如果 HVG 過少，下游分析最可能出現的問題是？",
            stem_en:"If HVGs are too few, what problem most likely arises downstream?",
            A:"PCA 不收斂", A_en:"PCA fails to converge",
            B:"無法捕捉到部分稀有亞群的訊號，造成分群解析力下降", B_en:"Signals of some rare subpopulations are missed, reducing clustering resolution",
            C:"運算速度變慢", C_en:"Computation becomes slower",
            D:"細胞會被刪除", D_en:"Cells get deleted",
            ans:"B",
            exp:"特徵不足會錯過稀有族群的代表基因；尤其稀有亞群可能因此無法被分出。",
            exp_en:"Insufficient features miss the genes that distinguish rare populations, which then fail to separate." },
          { type:"tf",
            stem:"是非題：HVG 的選擇結果只與資料有關，與 normalization 方法無關。",
            stem_en:"True/False: HVG selection depends only on the data, not on the normalization method used.",
            ans:"F",
            exp:"不同 normalization 會改變 mean-variance 關係，因此影響 HVG 排序與挑選結果。",
            exp_en:"Different normalizations alter the mean-variance relationship, affecting HVG ranking and selection." },
          { type:"single",
            stem:"當資料來源跨多個批次時，挑選 HVGs 的建議做法為？",
            stem_en:"When data come from multiple batches, what is the recommended HVG selection approach?",
            A:"全部合併後挑一次 HVGs", A_en:"Merge everything and pick HVGs once",
            B:"每個批次分別挑 HVGs 後取交集或聯集，再進入整合", B_en:"Pick HVGs per batch, then take intersection or union before integration",
            C:"完全不挑 HVG", C_en:"Skip HVG selection entirely",
            D:"只挑變異最低的基因", D_en:"Pick the lowest-variance genes",
            ans:"B",
            exp:"分批挑 HVGs 可避免批次效應主導 HVG 名單；Seurat/Harmony 工作流也採此策略。",
            exp_en:"Per-batch HVG selection avoids batch effects dominating the HVG list — used in Seurat/Harmony workflows." },
          { type:"single",
            stem:"下列何者最能說明 HVG 與「mean–variance 關係」的關聯？",
            stem_en:"Which best describes the relationship between HVGs and 'mean–variance'?",
            A:"高 mean 必為 HVG", A_en:"High mean implies HVG",
            B:"理想的 HVG 在校正過 mean–variance 趨勢後，其變異仍高於背景期望", B_en:"An ideal HVG still has variance above background expectation after correcting for the mean-variance trend",
            C:"HVG 都是低表達基因", C_en:"HVGs are all low-expression genes",
            D:"HVG 與 mean–variance 無關", D_en:"HVGs are unrelated to mean–variance",
            ans:"B",
            exp:"高表達基因通常變異也高，因此需先擬合 mean–variance 趨勢，挑選「相對於期望仍偏高」的基因。",
            exp_en:"High-mean genes tend to have high variance too; we fit the trend and pick genes whose variance still exceeds expectation." }
        ],
        "Step 4：縮放 (Scaling)": [
          { type:"single",
            stem:"Scaling 的核心目的為何？",
            stem_en:"What is the core purpose of Scaling?",
            A:"消除細胞間定序深度差異", A_en:"Remove sequencing depth differences between cells",
            B:"以 z-score 標準化每個基因，使各基因在 PCA 中具有平等的權重", B_en:"Z-score standardize each gene so all genes have equal weight in PCA",
            C:"挑選 marker 基因", C_en:"Pick marker genes",
            D:"做 doublet 偵測", D_en:"Do doublet detection",
            ans:"B",
            exp:"Scaling = 對每個基因做 z-score：(x − μ) / σ，避免高表達基因主導 PCA。",
            exp_en:"Scaling = per-gene z-score: (x − μ) / σ, preventing high-expression genes from dominating PCA." },
          { type:"single",
            stem:"Scaling 公式 z = (x − μ) / σ 中，μ 與 σ 是？",
            stem_en:"In the Scaling formula z = (x − μ) / σ, what are μ and σ?",
            A:"細胞層級的平均與標準差", A_en:"Per-cell mean and standard deviation",
            B:"基因層級在所有細胞上的平均與標準差", B_en:"Per-gene mean and standard deviation across all cells",
            C:"全資料集所有 reads 的平均", C_en:"Average of all reads across the dataset",
            D:"批次的中位數", D_en:"Batch median",
            ans:"B",
            exp:"Scaling 是「以基因為單位」做標準化，因此 μ、σ 是該基因在所有細胞中的統計量。",
            exp_en:"Scaling standardizes per-gene; μ and σ are statistics computed across all cells for that gene." },
          { type:"tf",
            stem:"是非題：Scaling 與 Normalization 是同一件事，可以擇一執行即可。",
            stem_en:"True/False: Scaling and Normalization are the same — only one is needed.",
            ans:"F",
            exp:"Normalization 校正細胞間總量；Scaling 對基因做 z-score。兩者作用對象與目的皆不同。",
            exp_en:"Normalization corrects per-cell totals; Scaling does per-gene z-scoring. Different targets, different purposes." },
          { type:"single",
            stem:"若略過 Scaling 直接做 PCA，最可能出現的問題是？",
            stem_en:"If Scaling is skipped before PCA, what is the most likely issue?",
            A:"完全沒有差別", A_en:"No difference at all",
            B:"高表達基因方差大，會主導主成分方向，掩蓋真實生物訊號", B_en:"High-expression genes have large variance and dominate principal components, masking real biological signal",
            C:"無法計算特徵值", C_en:"Eigenvalues cannot be computed",
            D:"反而能更精準偵測 marker", D_en:"Marker detection becomes more precise",
            ans:"B",
            exp:"PCA 對方差敏感，沒有 scaling 時方差大的基因會壟斷前幾個主成分。",
            exp_en:"PCA is variance-sensitive; without scaling, high-variance genes monopolize the leading PCs." },
          { type:"single",
            stem:"Seurat 的 ScaleData() 預設只對哪些基因做縮放？",
            stem_en:"By default, Seurat's ScaleData() scales which genes?",
            A:"全部基因", A_en:"All genes",
            B:"由 FindVariableFeatures 選出的 HVGs", B_en:"HVGs from FindVariableFeatures",
            C:"只縮放 mitochondrial 基因", C_en:"Only mitochondrial genes",
            D:"完全不縮放", D_en:"None at all",
            ans:"B",
            exp:"預設僅對 HVGs 做 scaling 以節省記憶體；可指定 features=all 來縮放全部。",
            exp_en:"By default only HVGs are scaled to save memory; pass features=all to scale all genes." },
          { type:"multi",
            stem:"在 Scaling 步驟中，常見可選擇「regress out」的變數有哪些？（多選）",
            stem_en:"Which variables are commonly chosen to 'regress out' during Scaling? (Multiple)",
            A:"percent.mt（粒線體比例）", A_en:"percent.mt (mitochondrial fraction)",
            B:"細胞週期分數 S.Score / G2M.Score", B_en:"Cell cycle scores S.Score / G2M.Score",
            C:"批次資訊（在簡單情境下）", C_en:"Batch information (in simple cases)",
            D:"細胞顏色", D_en:"Cell color",
            ans:["A","B","C"],
            exp:"D 為虛構選項。MT%、cell cycle、batch 都是常見不希望主導 PCA 的技術/外部變異。",
            exp_en:"D is fictitious. MT%, cell cycle, batch are common unwanted technical/external sources of variation." },
          { type:"tf",
            stem:"是非題：在 SCTransform 流程中，已經內建相對應的 scaling，不需再呼叫 ScaleData()。",
            stem_en:"True/False: The SCTransform pipeline includes equivalent scaling internally; ScaleData() is not needed afterwards.",
            ans:"T",
            exp:"SCTransform 輸出的是已建模的 Pearson residuals，已包含尺度標準化的效果。",
            exp_en:"SCTransform outputs modeled Pearson residuals, which already incorporate scale standardization." },
          { type:"single",
            stem:"關於 ScaleData 的 vars.to.regress 參數，下列何者正確？",
            stem_en:"Regarding ScaleData's vars.to.regress parameter, which is correct?",
            A:"用來移除低品質細胞", A_en:"Removes low-quality cells",
            B:"用來在 scaling 過程中移除指定變數對表達的影響（線性回歸殘差）", B_en:"Removes the effect of specified variables on expression during scaling (linear regression residuals)",
            C:"用來重新挑選 HVG", C_en:"Re-selects HVGs",
            D:"用於 trajectory 分析", D_en:"Used for trajectory analysis",
            ans:"B",
            exp:"vars.to.regress 透過線性模型移除指定變數所解釋的表達量，再回填殘差。",
            exp_en:"vars.to.regress fits a linear model to remove the variance explained by specified variables, returning residuals." },
          { type:"single",
            stem:"下列敘述何者最為正確？",
            stem_en:"Which statement is most correct?",
            A:"Scaling 後的數值是絕對表達量", A_en:"Scaled values are absolute expression amounts",
            B:"Scaling 後的值是相對於該基因平均的標準差倍數，可正可負", B_en:"Scaled values are signed multiples of standard deviation relative to that gene's mean",
            C:"Scaling 後一定大於 0", C_en:"Scaled values are always positive",
            D:"Scaling 結果與 normalization 無關", D_en:"Scaling is unrelated to normalization",
            ans:"B",
            exp:"z-score 是無量綱的，可正可負；負值代表低於該基因平均，正值代表高於平均。",
            exp_en:"Z-scores are dimensionless and signed; negative means below the gene's mean, positive means above." },
          { type:"tf",
            stem:"是非題：對沒有做 normalization 的原始 count，直接 z-score scaling 也能取得理想結果。",
            stem_en:"True/False: Z-score scaling can yield ideal results directly on raw counts without prior normalization.",
            ans:"F",
            exp:"原始 counts 受深度差異主導，未先 normalization 再 scaling 會把技術變異視為真實生物變異。",
            exp_en:"Raw counts are dominated by depth differences; scaling without prior normalization treats technical variation as biology." }
        ],
        "Step 5：主成分分析 (PCA)": [
          { type:"single",
            stem:"PCA 在 scRNA-seq 流程中的主要功能為何？",
            stem_en:"What is PCA's main role in the scRNA-seq pipeline?",
            A:"挑選 marker", A_en:"Pick markers",
            B:"從上千個 HVG 維度壓縮到數十個主成分，去除噪音並加速下游", B_en:"Compress thousands of HVG dimensions into tens of components, denoising and speeding up downstream",
            C:"做差異表達檢定", C_en:"Test differential expression",
            D:"做 doublet 偵測", D_en:"Do doublet detection",
            ans:"B",
            exp:"PCA 是 scRNA-seq 進入 graph-based 聚類與 UMAP 之前必經的線性降維步驟。",
            exp_en:"PCA is the linear dimensionality reduction step before graph-based clustering and UMAP in scRNA-seq." },
          { type:"single",
            stem:"用 Elbow plot 決定 nPCs 時，「elbow（手肘）」指的是？",
            stem_en:"In an Elbow plot for choosing nPCs, what is the 'elbow'?",
            A:"曲線的最低點", A_en:"The lowest point of the curve",
            B:"變異解釋率隨主成分增加而開始趨於平緩的轉折點", B_en:"The bend where variance explained begins to flatten",
            C:"曲線的最高點", C_en:"The highest point",
            D:"任意一個切點", D_en:"Any tangent point",
            ans:"B",
            exp:"Elbow plot 觀察方差解釋遞減的肘部，後面的主成分多為雜訊。",
            exp_en:"The elbow plot reveals the bend where variance explained tapers; PCs beyond it are mostly noise." },
          { type:"tf",
            stem:"是非題：選擇的 nPCs 越多越好，越能保留生物訊號。",
            stem_en:"True/False: More nPCs is always better and preserves more biological signal.",
            ans:"F",
            exp:"後段 PC 多為雜訊，反而會干擾近鄰圖與聚類；nPCs 過多可能放大批次或技術噪音。",
            exp_en:"Late PCs are mostly noise and disturb the neighbor graph and clustering; too many nPCs amplify batch/technical noise." },
          { type:"multi",
            stem:"關於 PCA 的特性，下列敘述何者正確？（多選）",
            stem_en:"Which statements about PCA are correct? (Multiple)",
            A:"PCA 是線性降維", A_en:"PCA is a linear dimensionality reduction",
            B:"PCA 找出方差最大的方向", B_en:"PCA finds directions of maximum variance",
            C:"PCA 完全等價於 UMAP", C_en:"PCA is equivalent to UMAP",
            D:"PC 之間互相正交", D_en:"PCs are mutually orthogonal",
            ans:["A","B","D"],
            exp:"C 錯誤：PCA 是線性方法，UMAP 是非線性流形學習。",
            exp_en:"C is wrong: PCA is linear; UMAP is non-linear manifold learning." },
          { type:"single",
            stem:"以下哪一項是設定 nPCs 的常見啟發式範圍？",
            stem_en:"Which is a common heuristic range for setting nPCs?",
            A:"1–2", A_en:"1–2",
            B:"5", B_en:"5",
            C:"10–50（依資料複雜度而異）", C_en:"10–50 (depending on data complexity)",
            D:"500 以上", D_en:"500 or more",
            ans:"C",
            exp:"PBMC 等實務資料常設 10–30；複雜異質資料可到 50。需配合 elbow / JackStraw 判斷。",
            exp_en:"Practical PBMC datasets often use 10–30; complex heterogeneous data may go to 50. Decide via elbow / JackStraw." },
          { type:"single",
            stem:"在 Seurat 工作流中，PCA 的輸入通常是？",
            stem_en:"In a Seurat workflow, what is typically the input to PCA?",
            A:"原始 count 矩陣", A_en:"Raw count matrix",
            B:"已 scale 過的 HVG 表達矩陣", B_en:"Scaled HVG expression matrix",
            C:"GTF 檔案", C_en:"GTF file",
            D:"Cellranger 的 BAM", D_en:"Cellranger BAM",
            ans:"B",
            exp:"流程：Normalize → HVGs → Scale → PCA。PCA 輸入為 scaled HVG matrix。",
            exp_en:"Pipeline: Normalize → HVGs → Scale → PCA. The input is the scaled HVG matrix." },
          { type:"tf",
            stem:"是非題：PCA 也能達到「去噪」的效果，因為丟棄低方差主成分等於濾掉雜訊。",
            stem_en:"True/False: PCA also achieves 'denoising' since discarding low-variance PCs filters out noise.",
            ans:"T",
            exp:"PCA 將訊號集中於前幾個 PC，後段 PC 多為隨機雜訊，截斷後相當於降噪。",
            exp_en:"PCA concentrates signal in the leading PCs; trailing PCs are mostly random noise. Truncation is effectively denoising." },
          { type:"single",
            stem:"Seurat 的 JackStraw / ElbowPlot 主要用途是？",
            stem_en:"What are Seurat's JackStraw / ElbowPlot mainly used for?",
            A:"挑選 HVG", A_en:"Pick HVGs",
            B:"判斷哪些 PC 帶有顯著訊號，協助決定 nPCs", B_en:"Identify which PCs carry significant signal to help choose nPCs",
            C:"做 trajectory", C_en:"Trajectory analysis",
            D:"做差異表達", D_en:"Differential expression",
            ans:"B",
            exp:"JackStraw 透過置換檢定每個 PC 的顯著性；ElbowPlot 看 SD 變化趨勢。",
            exp_en:"JackStraw uses permutation tests for PC significance; ElbowPlot shows SD trends." },
          { type:"single",
            stem:"當 nPCs 設定明顯不足，最可能的後果是？",
            stem_en:"If nPCs is clearly too small, what is the most likely consequence?",
            A:"電腦記憶體爆炸", A_en:"Memory blow-up",
            B:"分群解析度過低，部分稀有亞群會被合併", B_en:"Insufficient clustering resolution; some rare subpopulations get merged",
            C:"基因被刪除", C_en:"Genes get removed",
            D:"細胞數變多", D_en:"More cells appear",
            ans:"B",
            exp:"PCs 不足會丟失亞群區分訊號，常見現象是預期的細分群無法切開。",
            exp_en:"Too few PCs lose subpopulation-discriminating signal; expected fine subgroups cannot be separated." },
          { type:"tf",
            stem:"是非題：PCA 的輸出可直接做為 graph-based clustering 與 UMAP 的輸入。",
            stem_en:"True/False: PCA output can be directly used as input for graph-based clustering and UMAP.",
            ans:"T",
            exp:"FindNeighbors、RunUMAP 都接受 dims=1:nPCs 參數，直接用 PCA embedding。",
            exp_en:"FindNeighbors and RunUMAP accept dims=1:nPCs and use the PCA embedding directly." }
        ],
        "Step 6：聚類 (Clustering)": [
          { type:"single",
            stem:"Seurat / Scanpy 主流的聚類屬於哪一類？",
            stem_en:"Which family does mainstream clustering in Seurat/Scanpy belong to?",
            A:"K-means", A_en:"K-means",
            B:"Graph-based（KNN/SNN + Louvain/Leiden）", B_en:"Graph-based (KNN/SNN + Louvain/Leiden)",
            C:"Hierarchical clustering", C_en:"Hierarchical clustering",
            D:"DBSCAN", D_en:"DBSCAN",
            ans:"B",
            exp:"scRNA-seq 主流為 graph-based：先建 KNN 圖、加 SNN 權重，再以 Louvain/Leiden 做社群偵測。",
            exp_en:"scRNA-seq mainstream is graph-based: build KNN, add SNN weights, then community detection by Louvain/Leiden." },
          { type:"single",
            stem:"提高 resolution 參數會造成？",
            stem_en:"Increasing the resolution parameter will?",
            A:"群數變少、合併", A_en:"Fewer, merged clusters",
            B:"群數變多、切得更細", B_en:"More, finer clusters",
            C:"完全不影響", C_en:"No effect",
            D:"刪除 doublet", D_en:"Delete doublets",
            ans:"B",
            exp:"resolution 越大，社群偵測越偏好切割；常見區間 0.4–1.2，需依資料調整。",
            exp_en:"Higher resolution biases community detection toward more splitting; typical range 0.4–1.2, data-dependent." },
          { type:"tf",
            stem:"是非題：Graph-based 聚類需要使用者預先指定 K（群數）。",
            stem_en:"True/False: Graph-based clustering requires the user to predefine K (number of clusters).",
            ans:"F",
            exp:"Graph-based 不需預設 K；K-means 才需要。Graph-based 透過 resolution 控制粗細。",
            exp_en:"Graph-based does not predefine K; K-means does. Graph-based controls granularity via resolution." },
          { type:"multi",
            stem:"下列哪些是 Graph-based 聚類相對於 K-means 的優勢？（多選）",
            stem_en:"Which are advantages of graph-based clustering over K-means? (Multiple)",
            A:"不必預先指定群數", A_en:"No need to predefine cluster count",
            B:"能處理非凸形狀的細胞群", B_en:"Handles non-convex cluster shapes",
            C:"更適合 scRNA-seq 高維資料", C_en:"Better suited for scRNA-seq high-dimensional data",
            D:"完全不需要 PCA", D_en:"No PCA needed at all",
            ans:["A","B","C"],
            exp:"D 錯：實務上仍以 PCA embedding 計算 KNN 距離。",
            exp_en:"D is wrong: in practice KNN distances are computed on PCA embeddings." },
          { type:"single",
            stem:"Seurat 預設 KNN 參數 k.param = 20，意義為？",
            stem_en:"What does Seurat's default KNN parameter k.param = 20 mean?",
            A:"挑 20 個 HVGs", A_en:"Pick 20 HVGs",
            B:"每個細胞在 PCA 空間中找最近的 20 個鄰居建立網絡", B_en:"Each cell builds a network with its 20 nearest neighbors in PCA space",
            C:"只跑 20 個細胞", C_en:"Run only 20 cells",
            D:"切成 20 群", D_en:"Cut into 20 clusters",
            ans:"B",
            exp:"k 控制 KNN 圖的鄰居數，影響圖的稀疏度與分群粒度。",
            exp_en:"k controls KNN graph neighbor count, affecting graph sparsity and clustering granularity." },
          { type:"single",
            stem:"SNN 權重的目的是？",
            stem_en:"What is the purpose of SNN weights?",
            A:"用 read counts 加權", A_en:"Weight by read counts",
            B:"以「共同鄰居」加權鞏固穩定的鄰居關係，提高聚類穩定性", B_en:"Use 'shared neighbors' to weight stable neighbor relationships and stabilize clustering",
            C:"刪除 doublet", C_en:"Delete doublets",
            D:"挑選 HVG", D_en:"Pick HVGs",
            ans:"B",
            exp:"Shared Nearest Neighbor 用兩個細胞的共同鄰居數作為邊權，能抑制偽連結。",
            exp_en:"Shared Nearest Neighbor uses shared-neighbor count as edge weight, suppressing spurious links." },
          { type:"tf",
            stem:"是非題：resolution 並非越高越好，過高會導致虛假切割（過度聚類）。",
            stem_en:"True/False: Higher resolution isn't always better — excessively high values cause spurious splits (over-clustering).",
            ans:"T",
            exp:"過度聚類會把同一細胞類型切成多個無意義小群；建議搭配 marker 與穩定性評估。",
            exp_en:"Over-clustering splits one cell type into many meaningless subclusters; pair with marker checks and stability assessment." },
          { type:"single",
            stem:"下列何者「不是」 Louvain / Leiden 演算法的特性？",
            stem_en:"Which is NOT a characteristic of Louvain / Leiden?",
            A:"屬於社群偵測法", A_en:"Community detection method",
            B:"基於模塊度（modularity）最佳化", B_en:"Optimizes modularity",
            C:"必須事先指定群數", C_en:"Requires predefining cluster count",
            D:"是 scRNA-seq 主流分群法", D_en:"Mainstream clustering method in scRNA-seq",
            ans:"C",
            exp:"Louvain/Leiden 不需要事先指定群數，群數由演算法與 resolution 共同決定。",
            exp_en:"Louvain/Leiden do NOT predefine cluster count; it emerges from the algorithm and resolution." },
          { type:"single",
            stem:"若懷疑分群結果受「批次效應」干擾，下列做法何者最直接？",
            stem_en:"If you suspect clustering is confounded by batch effects, what is the most direct remedy?",
            A:"降低 resolution 強行合併", A_en:"Lower resolution to force merging",
            B:"檢查每群批次組成、必要時做 integration（如 Harmony）", B_en:"Inspect per-cluster batch composition and integrate if needed (e.g., Harmony)",
            C:"重新做 doublet 偵測", C_en:"Redo doublet detection",
            D:"只看 marker 即可不必整合", D_en:"Just rely on markers, no integration needed",
            ans:"B",
            exp:"當聚類主要反映樣本來源而非生物，應做 integration 校正。",
            exp_en:"When clustering reflects sample origin rather than biology, integrate to correct." },
          { type:"single",
            stem:"關於 Leiden 相較 Louvain 的改進，下列何者正確？",
            stem_en:"Regarding Leiden's improvements over Louvain, which is correct?",
            A:"完全不一樣的演算法理論", A_en:"Entirely different theoretical basis",
            B:"Leiden 改善了 Louvain 可能產生不連通群的問題，結果更穩定", B_en:"Leiden fixes Louvain's possibility of producing disconnected communities, giving more stable results",
            C:"Leiden 不再需要 graph", C_en:"Leiden no longer needs a graph",
            D:"Leiden 必須指定 K", D_en:"Leiden must specify K",
            ans:"B",
            exp:"Leiden 透過細化步驟保證每個群內部都是連通的，是 Louvain 的進化版。",
            exp_en:"Leiden adds a refinement step ensuring each community is internally connected — an evolution of Louvain." },
          { type:"multi",
            stem:"下列哪些是聚類常見的陷阱？（多選）",
            stem_en:"Which are common clustering pitfalls? (Multiple)",
            A:"過度聚類（resolution 太高）", A_en:"Over-clustering (resolution too high)",
            B:"忽略 doublets 形成假亞群", B_en:"Ignoring doublets, creating fake subpopulations",
            C:"沒處理批次效應，分群反映樣本來源", C_en:"Ignoring batch effects so clustering reflects sample origin",
            D:"使用 graph-based 聚類本身", D_en:"Using graph-based clustering itself",
            ans:["A","B","C"],
            exp:"D 不是陷阱本身；A、B、C 都是真實會誤導分析的常見問題。",
            exp_en:"D is not a pitfall; A/B/C are real issues that mislead analyses." }
        ],
        "Step 7：UMAP 視覺化": [
          { type:"single",
            stem:"UMAP 的主要用途為何？",
            stem_en:"What is the main purpose of UMAP?",
            A:"做差異表達檢定", A_en:"Differential expression testing",
            B:"非線性降維至 2D，便於視覺化細胞群分佈", B_en:"Non-linear reduction to 2D for visualizing cell distribution",
            C:"取代 PCA 直接餵給聚類", C_en:"Replace PCA as input to clustering",
            D:"做 doublet 偵測", D_en:"Doublet detection",
            ans:"B",
            exp:"UMAP 是非線性流形學習，將高維資料投影到 2D/3D，是 scRNA-seq 標準視覺化方法。",
            exp_en:"UMAP is non-linear manifold learning that projects high-dimensional data to 2D/3D — the standard scRNA-seq visualization." },
          { type:"single",
            stem:"UMAP 上兩個 cluster 距離很近，最謹慎的解讀為？",
            stem_en:"Two clusters appear close on UMAP — what is the most cautious interpretation?",
            A:"它們一定是同一細胞類型", A_en:"They must be the same cell type",
            B:"UMAP 的二維距離不一定精準對應分子相似度，需配合表達或 trajectory 進一步驗證", B_en:"UMAP's 2D distances do not perfectly reflect molecular similarity; verify with expression or trajectory",
            C:"它們表達完全相同", C_en:"They express identically",
            D:"它們屬於不同 batch", D_en:"They belong to different batches",
            ans:"B",
            exp:"UMAP 主要保留鄰近結構，全局距離可能扭曲；不能單憑視覺距離下結論。",
            exp_en:"UMAP preserves local neighborhood; global distances can be distorted. Visual proximity alone is unreliable." },
          { type:"tf",
            stem:"是非題：UMAP 的座標數值具有絕對的生物學意義，可直接用於分析。",
            stem_en:"True/False: UMAP coordinates have absolute biological meaning and can be analyzed directly.",
            ans:"F",
            exp:"UMAP 為視覺化用途，座標僅相對；不應對 UMAP1/UMAP2 直接做下游統計推論。",
            exp_en:"UMAP is for visualization; coordinates are only relative. Don't run downstream statistics directly on UMAP1/UMAP2." },
          { type:"multi",
            stem:"關於 UMAP vs t-SNE，下列敘述何者正確？（多選）",
            stem_en:"Regarding UMAP vs t-SNE, which statements are correct? (Multiple)",
            A:"UMAP 對全局結構保留通常較佳", A_en:"UMAP usually preserves global structure better",
            B:"UMAP 在大資料集上速度通常較快", B_en:"UMAP is usually faster on large datasets",
            C:"t-SNE 結果隨機性較大、可重複性較弱", C_en:"t-SNE has more randomness and weaker reproducibility",
            D:"UMAP 是線性方法", D_en:"UMAP is a linear method",
            ans:["A","B","C"],
            exp:"D 錯：UMAP 是非線性方法。",
            exp_en:"D is wrong: UMAP is non-linear." },
          { type:"single",
            stem:"UMAP 的 n_neighbors 參數變大，通常會？",
            stem_en:"Increasing UMAP's n_neighbors usually:",
            A:"更注重局部結構", A_en:"Emphasize local structure more",
            B:"更強調全局結構，群體間關係會更平滑", B_en:"Emphasize global structure; inter-cluster relations become smoother",
            C:"刪除細胞", C_en:"Delete cells",
            D:"等於 doublet 偵測", D_en:"Equivalent to doublet detection",
            ans:"B",
            exp:"n_neighbors 大則考慮更多鄰居，傾向保留全局；小則強調局部。",
            exp_en:"Larger n_neighbors considers more neighbors, favoring global structure; smaller favors local." },
          { type:"single",
            stem:"min_dist 增加，UMAP 的視覺結果會？",
            stem_en:"Increasing min_dist makes UMAP look:",
            A:"群體更緊縮", A_en:"More tightly packed clusters",
            B:"群體更分散，群內結構較不擁擠", B_en:"More spread out, less crowded within clusters",
            C:"完全不變", C_en:"No change",
            D:"刪除離群細胞", D_en:"Removes outlier cells",
            ans:"B",
            exp:"min_dist 控制低維點之間最小距離，越大越不擠。",
            exp_en:"min_dist controls minimum distance in low-dim space; larger values reduce crowding." },
          { type:"tf",
            stem:"是非題：固定隨機種子（seed）後，UMAP 結果可重現。",
            stem_en:"True/False: With a fixed random seed, UMAP results are reproducible.",
            ans:"T",
            exp:"UMAP 含隨機初始化，固定 seed 即可獲得相同投影，便於論文重現。",
            exp_en:"UMAP has random initialization; fixing the seed yields identical projections, useful for reproducibility." },
          { type:"single",
            stem:"UMAP 投影預設輸入應該是？",
            stem_en:"What should the default input to UMAP be?",
            A:"原始 counts", A_en:"Raw counts",
            B:"PCA 降維後的 embedding（dims=1:nPCs）", B_en:"PCA embedding (dims=1:nPCs)",
            C:"VlnPlot 結果", C_en:"VlnPlot output",
            D:"GO term", D_en:"GO terms",
            ans:"B",
            exp:"以 PCA embedding 計算近鄰圖再做 UMAP，是 Seurat/Scanpy 標準做法。",
            exp_en:"Computing the neighbor graph on PCA embedding then running UMAP is the Seurat/Scanpy standard." },
          { type:"single",
            stem:"以下何者「不是」UMAP 的主要設計目的？",
            stem_en:"Which is NOT UMAP's main design purpose?",
            A:"視覺化", A_en:"Visualization",
            B:"降維", B_en:"Dimensionality reduction",
            C:"取代 PCA 做聚類前的線性降維", C_en:"Replace PCA as the linear pre-clustering reduction",
            D:"觀察細胞群相對關係", D_en:"Observing cell-cluster relationships",
            ans:"C",
            exp:"UMAP 通常不取代 PCA 做為聚類輸入；聚類仍以 PCA embedding 為主，UMAP 主要用於可視化。",
            exp_en:"UMAP doesn't usually replace PCA for clustering input; clustering uses PCA embeddings, UMAP is for visualization." },
          { type:"multi",
            stem:"下列哪些做法可以幫助 UMAP 圖更具說服力？（多選）",
            stem_en:"Which practices make a UMAP plot more convincing? (Multiple)",
            A:"按 cluster 上色比對 marker", A_en:"Color by cluster and compare with markers",
            B:"按 batch 上色檢查整合效果", B_en:"Color by batch to check integration",
            C:"列出座標數值絕對解讀", C_en:"List coordinate values for absolute interpretation",
            D:"標註標誌基因位置", D_en:"Annotate marker gene positions",
            ans:["A","B","D"],
            exp:"C 錯誤；UMAP 數值不可絕對解讀。",
            exp_en:"C is wrong; UMAP coordinates cannot be interpreted absolutely." }
        ],
        "Step 8：細胞註釋 (Annotation)": [
          { type:"single",
            stem:"細胞註釋的目的是？",
            stem_en:"What is the purpose of cell annotation?",
            A:"從聚類得到的數字標籤對應到實際細胞類型名稱", A_en:"Map numeric cluster labels to real cell-type names",
            B:"找出 doublet", B_en:"Find doublets",
            C:"做 PCA", C_en:"Do PCA",
            D:"消除批次效應", D_en:"Remove batch effects",
            ans:"A",
            exp:"聚類僅產生數字 cluster；註釋是把它對應到生物學上的細胞型態（如 T cell、B cell）。",
            exp_en:"Clustering produces numeric clusters; annotation maps them to biological cell types (e.g., T cell, B cell)." },
          { type:"single",
            stem:"PBMC 中，CD3D + IL7R + CD4（高）的 cluster 最可能是？",
            stem_en:"In PBMC, a cluster with high CD3D + IL7R + CD4 is most likely?",
            A:"CD8+ T", A_en:"CD8+ T",
            B:"CD4+ T", B_en:"CD4+ T",
            C:"B cell", C_en:"B cell",
            D:"NK cell", D_en:"NK cell",
            ans:"B",
            exp:"CD3D 為 T 細胞核心 marker；CD4/IL7R 偏向 CD4+ helper T。",
            exp_en:"CD3D is a core T-cell marker; CD4/IL7R lean toward CD4+ helper T." },
          { type:"single",
            stem:"MS4A1 (CD20)、CD79A 高表達最可能是哪種細胞？",
            stem_en:"High expression of MS4A1 (CD20) and CD79A most likely indicates which cell type?",
            A:"B cell", A_en:"B cell",
            B:"CD8+ T", B_en:"CD8+ T",
            C:"NK cell", C_en:"NK cell",
            D:"Monocyte", D_en:"Monocyte",
            ans:"A",
            exp:"MS4A1/CD79A 是 B 細胞經典 marker。",
            exp_en:"MS4A1/CD79A are canonical B-cell markers." },
          { type:"single",
            stem:"GNLY、NKG7、KLRD1 高表達最可能對應？",
            stem_en:"High GNLY, NKG7, KLRD1 most likely corresponds to:",
            A:"NK cell", A_en:"NK cell",
            B:"B cell", B_en:"B cell",
            C:"DC", C_en:"DC",
            D:"Platelet", D_en:"Platelet",
            ans:"A",
            exp:"GNLY/NKG7/KLRD1 為 NK 細胞特徵基因。",
            exp_en:"GNLY/NKG7/KLRD1 are NK-cell signature genes." },
          { type:"multi",
            stem:"下列哪些是常用的細胞註釋策略？（多選）",
            stem_en:"Which are common annotation strategies? (Multiple)",
            A:"差異表達分析找 markers，再對照已知標誌基因", A_en:"DE analysis to find markers, then compare with known signatures",
            B:"自動註釋工具（如 SingleR、CellTypist、Azimuth）", B_en:"Automatic tools (SingleR, CellTypist, Azimuth)",
            C:"領域專家手動驗證（黃金標準）", C_en:"Domain expert manual validation (gold standard)",
            D:"隨機指派細胞名稱", D_en:"Randomly assign cell-type names",
            ans:["A","B","C"],
            exp:"D 不是合理策略。註釋的三大策略：手動 markers、自動工具、專家驗證。",
            exp_en:"D is not valid. The three pillars: manual markers, automated tools, expert validation." },
          { type:"tf",
            stem:"是非題：自動註釋工具的結果可直接視為最終答案，不需任何驗證。",
            stem_en:"True/False: Automated annotation results can be treated as final without any verification.",
            ans:"F",
            exp:"自動工具仍可能誤判罕見/新型細胞，需人工驗證 marker 表達是否合理。",
            exp_en:"Automatic tools can still misclassify rare/novel cells; manual marker checks are needed." },
          { type:"single",
            stem:"CD14、LYZ、S100A8 高表達最可能對應？",
            stem_en:"High CD14, LYZ, S100A8 most likely corresponds to:",
            A:"CD14+ Monocyte", A_en:"CD14+ Monocyte",
            B:"B cell", B_en:"B cell",
            C:"CD8+ T", C_en:"CD8+ T",
            D:"Platelet", D_en:"Platelet",
            ans:"A",
            exp:"CD14、LYZ 是經典 monocyte marker。",
            exp_en:"CD14 and LYZ are canonical monocyte markers." },
          { type:"single",
            stem:"PPBP、PF4 高表達常見於？",
            stem_en:"High PPBP and PF4 expression is commonly seen in:",
            A:"Platelet（血小板）", A_en:"Platelet",
            B:"NK cell", B_en:"NK cell",
            C:"DC", C_en:"DC",
            D:"CD4+ T", D_en:"CD4+ T",
            ans:"A",
            exp:"PPBP（β-thromboglobulin）與 PF4 是血小板標誌基因。",
            exp_en:"PPBP (β-thromboglobulin) and PF4 are platelet marker genes." },
          { type:"multi",
            stem:"下列哪些是常見的自動註釋工具？（多選）",
            stem_en:"Which are common automated annotation tools? (Multiple)",
            A:"SingleR", A_en:"SingleR",
            B:"CellTypist", B_en:"CellTypist",
            C:"Azimuth", C_en:"Azimuth",
            D:"Seurat::FindAllMarkers", D_en:"Seurat::FindAllMarkers",
            ans:["A","B","C"],
            exp:"D 是找 marker 的函式，不是註釋工具本身。",
            exp_en:"D is a marker-finding function, not an annotation tool itself." },
          { type:"single",
            stem:"在註釋時，下列哪一項是最重要的「健全性檢查」？",
            stem_en:"During annotation, which is the most important 'sanity check'?",
            A:"colour 風格美觀", A_en:"Aesthetic color choices",
            B:"檢查指派的細胞類型其 canonical marker 在該 cluster 是否確實高表達", B_en:"Verify the canonical markers of the assigned cell type are indeed highly expressed in that cluster",
            C:"檢查檔名是否英文", C_en:"Check whether filenames are in English",
            D:"看 UMAP 形狀漂亮", D_en:"Make UMAP look pretty",
            ans:"B",
            exp:"Marker 必須在指派的細胞群中高表達，否則註釋不可信。",
            exp_en:"Markers must be highly expressed in the assigned cluster, otherwise the annotation is unreliable." },
          { type:"tf",
            stem:"是非題：Dot plot 是觀察多個 marker 在多個 cluster 中表達高低的好工具。",
            stem_en:"True/False: Dot plot is a good tool to view multiple markers across multiple clusters.",
            ans:"T",
            exp:"Dot plot 同時呈現平均表達量（顏色）與表達細胞比例（點大小），是 marker 視覺檢查的常用工具。",
            exp_en:"Dot plot shows mean expression (color) and percent expressing (dot size) — a standard marker visualization." }
        ],
        "Step 9：差異表達分析 (DE)": [
          { type:"single",
            stem:"DE 分析中「找 cluster markers」的常見邏輯為？",
            stem_en:"What is the common logic of 'finding cluster markers' in DE analysis?",
            A:"比較該 cluster 與其他所有 cluster，找出顯著上調基因", A_en:"Compare a cluster against all others to find significantly upregulated genes",
            B:"任意挑兩細胞比較", B_en:"Pick any two cells to compare",
            C:"使用 PCA 取代 DE", C_en:"Use PCA instead of DE",
            D:"看 UMAP 顏色判斷", D_en:"Judge by UMAP colors",
            ans:"A",
            exp:"FindAllMarkers 即此邏輯：one-vs-rest，找出特異上調基因供註釋使用。",
            exp_en:"FindAllMarkers follows one-vs-rest logic to surface upregulated genes for annotation." },
          { type:"single",
            stem:"在跨樣本/跨條件 DE 比較時，目前最佳實踐通常是？",
            stem_en:"For cross-sample / cross-condition DE, what is the current best practice?",
            A:"對每個細胞做 t-test", A_en:"Run t-test on every individual cell",
            B:"先把每個樣本同一細胞類型 pseudobulk 聚合，再以 DESeq2/edgeR 等 bulk 方法分析", B_en:"Pseudobulk per sample × cell-type, then apply bulk methods like DESeq2/edgeR",
            C:"完全不需做 DE", C_en:"DE is not needed at all",
            D:"只用 UMAP 判斷", D_en:"Just use UMAP",
            ans:"B",
            exp:"Pseudobulk + bulk 方法能控制偽複本問題（pseudo-replication），是當前推薦做法。",
            exp_en:"Pseudobulk + bulk methods control for pseudo-replication and are the current recommended practice." },
          { type:"tf",
            stem:"是非題：在跨條件比較時，將每個細胞當成獨立樣本做檢定（如直接用 Wilcoxon）會嚴重低估變異，造成大量假陽性。",
            stem_en:"True/False: In cross-condition tests, treating each cell as an independent sample (e.g., direct Wilcoxon) severely underestimates variance, producing many false positives.",
            ans:"T",
            exp:"細胞並非獨立生物複本；忽略樣本層級結構會讓 p 值過於樂觀，這是 pseudo-replication 問題。",
            exp_en:"Cells are not independent biological replicates; ignoring sample structure inflates p-values — pseudo-replication." },
          { type:"multi",
            stem:"下列哪些屬於 scRNA-seq 常見的 DE 方法？（多選）",
            stem_en:"Which are common DE methods in scRNA-seq? (Multiple)",
            A:"Wilcoxon rank-sum", A_en:"Wilcoxon rank-sum",
            B:"MAST（zero-inflated hurdle model）", B_en:"MAST (zero-inflated hurdle model)",
            C:"Pseudobulk + DESeq2/edgeR", C_en:"Pseudobulk + DESeq2/edgeR",
            D:"PCA", D_en:"PCA",
            ans:["A","B","C"],
            exp:"PCA 不是 DE 方法。",
            exp_en:"PCA is not a DE method." },
          { type:"single",
            stem:"火山圖（Volcano plot）通常的 X 軸與 Y 軸是？",
            stem_en:"What are the typical X and Y axes of a volcano plot?",
            A:"X: log2FC，Y: −log10(p-value)", A_en:"X: log2FC, Y: −log10(p-value)",
            B:"X: gene name，Y: cell ID", B_en:"X: gene name, Y: cell ID",
            C:"X: PC1，Y: PC2", C_en:"X: PC1, Y: PC2",
            D:"X: cluster，Y: count", D_en:"X: cluster, Y: count",
            ans:"A",
            exp:"Volcano plot：水平軸為效應大小（log2FC），垂直軸為顯著性（−log10 p）。",
            exp_en:"Volcano plot: x = effect size (log2FC), y = significance (−log10 p)." },
          { type:"single",
            stem:"設定 |log2FC| ≥ 1、p_adj < 0.05，意味著？",
            stem_en:"Setting |log2FC| ≥ 1 and p_adj < 0.05 means:",
            A:"基因至少有 2 倍變化且通過顯著性", A_en:"Genes have at least 2-fold change and pass significance",
            B:"完全沒過濾", B_en:"No filtering at all",
            C:"只看 p 值不看效應", C_en:"Only p-value, ignoring effect size",
            D:"自動排除所有基因", D_en:"Auto-excludes all genes",
            ans:"A",
            exp:"|log2FC|=1 即倍率變化 ≥ 2 倍；p_adj 控制多重檢定後的 false discovery。",
            exp_en:"|log2FC|=1 means ≥ 2-fold change; p_adj controls false discovery after multiple testing correction." },
          { type:"tf",
            stem:"是非題：MAST 是專為 scRNA-seq 設計、可處理零膨脹的 hurdle model。",
            stem_en:"True/False: MAST is a hurdle model designed for scRNA-seq that handles zero-inflation.",
            ans:"T",
            exp:"MAST 將表達分為「是否有表達」與「條件表達量」兩部分建模，適合稀疏資料。",
            exp_en:"MAST models expression as 'whether expressed' + 'conditional level' — suitable for sparse data." },
          { type:"single",
            stem:"FindMarkers 中 logfc.threshold 與 min.pct 參數作用為？",
            stem_en:"In FindMarkers, what do logfc.threshold and min.pct do?",
            A:"設定 PCA 維度", A_en:"Set PCA dimensions",
            B:"預先過濾差異不大的基因，加速計算", B_en:"Pre-filter genes with small differences to speed up computation",
            C:"指定細胞顏色", C_en:"Specify cell color",
            D:"控制 batch", D_en:"Control batch",
            ans:"B",
            exp:"logfc.threshold 過濾倍率變化過小；min.pct 要求基因至少在某比例細胞中表達。",
            exp_en:"logfc.threshold filters small fold changes; min.pct requires expression in a minimum proportion of cells." },
          { type:"single",
            stem:"「找 cluster marker」與「跨條件 DE」的核心差異在於？",
            stem_en:"What is the core difference between 'finding cluster markers' and 'cross-condition DE'?",
            A:"完全相同", A_en:"They are identical",
            B:"前者比較 cluster vs 其他 cluster；後者比較同一細胞類型在不同條件下的表達差異", B_en:"The former compares cluster vs other clusters; the latter compares the same cell type across conditions",
            C:"後者不需要統計", C_en:"The latter doesn't need statistics",
            D:"前者只用看 UMAP 即可", D_en:"The former only needs UMAP inspection",
            ans:"B",
            exp:"兩者目的與設計不同；找 marker 是分群描述，跨條件 DE 是回答生物學假設。",
            exp_en:"They serve different purposes: marker finding describes clusters, cross-condition DE answers biological hypotheses." },
          { type:"multi",
            stem:"下列哪些做法有助於減少 DE 假陽性？（多選）",
            stem_en:"Which practices help reduce DE false positives? (Multiple)",
            A:"使用 pseudobulk 處理跨樣本比較", A_en:"Use pseudobulk for cross-sample comparison",
            B:"使用 FDR/BH 校正多重檢定", B_en:"Apply FDR/BH multiple testing correction",
            C:"加入合理的 logfc.threshold 與 min.pct 過濾", C_en:"Add sensible logfc.threshold and min.pct filters",
            D:"忽略 batch 與 sample 結構", D_en:"Ignore batch and sample structure",
            ans:["A","B","C"],
            exp:"D 反而會增加假陽性。",
            exp_en:"D actually increases false positives." },
          { type:"tf",
            stem:"是非題：DE 分析永遠都應該設 |log2FC| ≥ 1，無例外。",
            stem_en:"True/False: DE analysis should always set |log2FC| ≥ 1 without exception.",
            ans:"F",
            exp:"門檻需依研究目的調整；某些細微但重要的轉錄因子變化可能 < 1 仍具生物意義。",
            exp_en:"Thresholds depend on research goals; some subtle but important transcription factor changes < 1 still have biological meaning." }
        ]
      },
      "進階分析主題": {
        "Advanced：資料整合 (Integration)": [
          { type:"single",
            stem:"當合併多批次資料時，UMAP 主要按「樣本來源」分群而非細胞類型，最可能代表？",
            stem_en:"When merging multi-batch data, if UMAP clusters mainly by 'sample origin' rather than cell type, this most likely indicates:",
            A:"資料完全乾淨，無批次效應", A_en:"Data is perfectly clean, no batch effect",
            B:"明顯的批次效應，需做 integration", B_en:"Strong batch effect; integration is needed",
            C:"細胞類型本來就一樣多", C_en:"Cell types just happen to be equal",
            D:"屬於 doublet", D_en:"It's all doublets",
            ans:"B",
            exp:"分群按樣本切開即典型 batch effect 訊號，需用整合方法（Harmony/CCA/RPCA/scVI）校正。",
            exp_en:"Clustering by sample is the classic batch-effect signal; correct with integration (Harmony/CCA/RPCA/scVI)." },
          { type:"single",
            stem:"Harmony 的核心邏輯為何？",
            stem_en:"What is the core logic of Harmony?",
            A:"在 PCA 空間中迭代校正，使同類細胞跨批次聚攏，運算快速且通用", A_en:"Iterative correction in PCA space to bring same-type cells together across batches; fast and general-purpose",
            B:"完全不需要 PCA", B_en:"Doesn't require PCA at all",
            C:"基於深度學習端到端建模", C_en:"End-to-end deep learning model",
            D:"只能用於 Smart-seq", D_en:"Only works for Smart-seq",
            ans:"A",
            exp:"Harmony 在 PCA embedding 上做 soft k-means 與線性校正，速度快、適用大資料。",
            exp_en:"Harmony performs soft k-means and linear correction on PCA embeddings — fast and scalable to large data." },
          { type:"multi",
            stem:"下列哪些屬於常見的 scRNA-seq integration 方法？（多選）",
            stem_en:"Which are common scRNA-seq integration methods? (Multiple)",
            A:"Harmony", A_en:"Harmony",
            B:"Seurat CCA / RPCA", B_en:"Seurat CCA / RPCA",
            C:"scVI", C_en:"scVI",
            D:"DoubletFinder", D_en:"DoubletFinder",
            ans:["A","B","C"],
            exp:"DoubletFinder 是 doublet 偵測工具，不是 integration。",
            exp_en:"DoubletFinder is for doublet detection, not integration." },
          { type:"single",
            stem:"Seurat v5 推出的 RPCA 相較 CCA 適用於？",
            stem_en:"Seurat v5's RPCA is preferable to CCA when:",
            A:"細胞組成相似時", A_en:"Cell compositions are similar",
            B:"當批次間細胞組成差異較大、CCA 易過度校正時", B_en:"Batches differ substantially in composition where CCA tends to over-correct",
            C:"做差異表達", C_en:"Doing differential expression",
            D:"做 trajectory", D_en:"Doing trajectory",
            ans:"B",
            exp:"RPCA（reciprocal PCA）對差異組成更穩健，避免 CCA 在跨組成差異時將不同型態強制對齊。",
            exp_en:"RPCA (reciprocal PCA) is more robust to composition differences and avoids CCA over-aligning unlike types." },
          { type:"tf",
            stem:"是非題：scVI 屬於變分自編碼器（VAE）類深度學習模型，能同時做 normalization 與 integration。",
            stem_en:"True/False: scVI is a VAE-based deep model that performs normalization and integration simultaneously.",
            ans:"T",
            exp:"scVI 以深度生成模型直接從原始 counts 建模，輸出潛在嵌入可用於下游聚類與整合。",
            exp_en:"scVI uses a deep generative model on raw counts and outputs a latent embedding usable for clustering and integration." },
          { type:"single",
            stem:"判斷整合是否成功，下列何者不是合理的方法？",
            stem_en:"Which is NOT a reasonable way to judge integration success?",
            A:"按 batch 上色看是否仍清楚分開", A_en:"Color by batch and check if they remain clearly separated",
            B:"按細胞類型 marker 看是否在同類細胞混合而成", B_en:"Use cell-type markers to check if same-type cells are mixed across batches",
            C:"觀察 UMAP 是否變得「漂亮」就足夠", C_en:"Just check if UMAP looks 'nice'",
            D:"使用 LISI / kBET 等定量指標", D_en:"Use quantitative metrics like LISI / kBET",
            ans:"C",
            exp:"UMAP「好看」是主觀，應使用定量指標與 marker 表達一併確認。",
            exp_en:"UMAP 'niceness' is subjective; use quantitative metrics and marker expression together." },
          { type:"single",
            stem:"以下哪一項不是 integration 想保留的東西？",
            stem_en:"Which is NOT something integration aims to preserve?",
            A:"真實的細胞類型差異", A_en:"True cell-type differences",
            B:"批次間的系統性技術差異", B_en:"Systematic technical differences between batches",
            C:"罕見亞群", C_en:"Rare subpopulations",
            D:"穩定的 marker 表達模式", D_en:"Stable marker expression patterns",
            ans:"B",
            exp:"Integration 想消除的正是批次間技術差異，並保留生物學差異。",
            exp_en:"Integration aims to remove technical differences between batches while preserving biology." },
          { type:"multi",
            stem:"下列哪些是「可能造成 batch effect」的因素？（多選）",
            stem_en:"Which factors can cause batch effects? (Multiple)",
            A:"試劑批號", A_en:"Reagent lots",
            B:"操作者技術", B_en:"Operator technique",
            C:"定序平台/版本", C_en:"Sequencing platform / version",
            D:"作圖軟體版本", D_en:"Plotting software version",
            ans:["A","B","C"],
            exp:"D 不是 batch effect 來源；前三者均為實驗系統性差異。",
            exp_en:"D is not a source; the first three are systematic experimental differences." },
          { type:"tf",
            stem:"是非題：過度整合可能把真正不同的細胞類型「強行對齊」，反而抹平生物差異。",
            stem_en:"True/False: Over-integration can forcibly align truly different cell types and erase biological differences.",
            ans:"T",
            exp:"過度校正會犧牲生物訊號，常見於對極不平衡批次強用 CCA 的情況。",
            exp_en:"Over-correction sacrifices biological signal — common when CCA is applied to highly imbalanced batches." },
          { type:"single",
            stem:"當資料規模極大、批次結構複雜，且需要保留細微亞群差異時，較合適的選擇通常是？",
            stem_en:"For very large data with complex batch structure and a need to preserve subtle subpopulations, the typical choice is:",
            A:"忽略整合", A_en:"Skip integration",
            B:"scVI / scANVI 等深度學習模型", B_en:"Deep learning models like scVI / scANVI",
            C:"Bulk RNA-seq", C_en:"Bulk RNA-seq",
            D:"只用 UMAP 視覺判斷", D_en:"Just visual UMAP inspection",
            ans:"B",
            exp:"scVI 系列在巨型異質資料上具優勢；對複雜批次結構表現穩健。",
            exp_en:"The scVI family excels on massive heterogeneous data with complex batch structures." }
        ],
        "Advanced：細胞通訊 (CellChat)": [
          { type:"single",
            stem:"細胞通訊分析的核心輸入是？",
            stem_en:"What is the core input for cell-cell communication analysis?",
            A:"細胞類型註釋後的 scRNA-seq 表達矩陣 + ligand–receptor 資料庫", A_en:"Annotated scRNA-seq expression matrix + ligand–receptor database",
            B:"DNA 甲基化資料", B_en:"DNA methylation data",
            C:"ChIP-seq 結果", C_en:"ChIP-seq results",
            D:"Hi-C 矩陣", D_en:"Hi-C matrix",
            ans:"A",
            exp:"L–R 分析需要分群註釋與 L–R 資料庫，方能評估細胞間訊號傳遞機率。",
            exp_en:"L–R analysis requires annotated clusters and an L–R database to estimate intercellular signaling probabilities." },
          { type:"single",
            stem:"CellChat 的核心建模邏輯是？",
            stem_en:"What is the core modeling logic of CellChat?",
            A:"以質量作用定律（mass action law）建模 L–R 互動機率", A_en:"Model L–R interaction probability via mass action law",
            B:"以 PCA 降維", B_en:"PCA dimensionality reduction",
            C:"以 KEGG enrichment 取代", C_en:"Replace with KEGG enrichment",
            D:"以 Doublet score 取代", D_en:"Replace with doublet score",
            ans:"A",
            exp:"CellChat 將 L 與 R 表達量代入 mass action 公式估算交互機率，並支援多種視覺化。",
            exp_en:"CellChat plugs ligand and receptor expression into mass action formulas to estimate interaction probability and supports rich visualization." },
          { type:"multi",
            stem:"下列哪些屬於常見細胞通訊分析工具？（多選）",
            stem_en:"Which are common cell communication tools? (Multiple)",
            A:"CellChat", A_en:"CellChat",
            B:"CellPhoneDB", B_en:"CellPhoneDB",
            C:"NicheNet", C_en:"NicheNet",
            D:"DoubletFinder", D_en:"DoubletFinder",
            ans:["A","B","C"],
            exp:"DoubletFinder 為 doublet 工具。",
            exp_en:"DoubletFinder is a doublet tool." },
          { type:"single",
            stem:"NicheNet 比 CellChat / CellPhoneDB 多了什麼能力？",
            stem_en:"What additional capability does NicheNet have over CellChat / CellPhoneDB?",
            A:"檢查樣本品質", A_en:"Check sample quality",
            B:"從 ligand 追蹤到下游受影響的目標基因，連結 L–R 與下游表達變化", B_en:"Trace ligands to downstream affected target genes, linking L–R to expression changes",
            C:"只支援 Python", C_en:"Python only",
            D:"做 trajectory 分析", D_en:"Trajectory analysis",
            ans:"B",
            exp:"NicheNet 結合先驗知識網絡，預測 ligand 對 receiver 細胞的下游基因影響。",
            exp_en:"NicheNet combines prior knowledge networks to predict downstream effects of ligands on receiver cells." },
          { type:"tf",
            stem:"是非題：CellPhoneDB 採用排列檢定（permutation test）來篩選顯著的 L–R pairs。",
            stem_en:"True/False: CellPhoneDB uses permutation tests to identify significant L–R pairs.",
            ans:"T",
            exp:"CellPhoneDB 透過 cluster label 隨機置換建立零分佈，篩出顯著互動。",
            exp_en:"CellPhoneDB permutes cluster labels to build a null distribution and identifies significant interactions." },
          { type:"single",
            stem:"下列關於 LIANA 的敘述，何者正確？",
            stem_en:"Which statement about LIANA is correct?",
            A:"是只做 trajectory 的工具", A_en:"It only does trajectory",
            B:"是整合多種 L–R 推斷方法的統一框架，可取共識結果", B_en:"It is a unified framework integrating multiple L–R methods to obtain consensus",
            C:"取代了 normalization", C_en:"Replaces normalization",
            D:"用於 doublet 偵測", D_en:"Used for doublet detection",
            ans:"B",
            exp:"LIANA 提供統一介面跑多家方法（CellChat/CellPhoneDB/NATMI 等），便於比較與共識。",
            exp_en:"LIANA provides a unified interface to run multiple methods (CellChat/CellPhoneDB/NATMI etc.) for comparison and consensus." },
          { type:"single",
            stem:"進行細胞通訊分析「之前」最不可省略的步驟是？",
            stem_en:"Which step is essential BEFORE running cell communication analysis?",
            A:"挑選顏色", A_en:"Pick colors",
            B:"先完成可信的細胞類型註釋", B_en:"Complete reliable cell-type annotation first",
            C:"做 trajectory", C_en:"Run trajectory",
            D:"做 ChIP-seq", D_en:"Run ChIP-seq",
            ans:"B",
            exp:"細胞通訊以 cell type 為單位估算；註釋錯誤會造成 L–R 推論錯誤。",
            exp_en:"Cell communication is computed per cell type; wrong annotation leads to wrong L–R inference." },
          { type:"multi",
            stem:"下列何者是常見的 L–R 視覺化方式？（多選）",
            stem_en:"Which are common L–R visualizations? (Multiple)",
            A:"圈狀圖（chord/circos）", A_en:"Chord / circos plot",
            B:"熱圖（heatmap of communication probability）", B_en:"Heatmap of communication probability",
            C:"river plot / Sankey", C_en:"River / Sankey plot",
            D:"火山圖", D_en:"Volcano plot",
            ans:["A","B","C"],
            exp:"火山圖屬於 DE 視覺化，與 L–R 無直接關聯。",
            exp_en:"Volcano plots are for DE, not directly related to L–R." },
          { type:"tf",
            stem:"是非題：CellChat 支援跨條件（如 disease vs control）的細胞通訊比較。",
            stem_en:"True/False: CellChat supports cross-condition (e.g., disease vs control) communication comparison.",
            ans:"T",
            exp:"CellChat 提供 mergeCellChat 與差異 pathway 比較工具，可做跨條件分析。",
            exp_en:"CellChat provides mergeCellChat and pathway differential tools for cross-condition analysis." },
          { type:"single",
            stem:"對於多亞基受體複合體（如 IL2RA/IL2RB/IL2RG），下列敘述何者正確？",
            stem_en:"For multi-subunit receptor complexes (e.g., IL2RA/IL2RB/IL2RG), which is correct?",
            A:"任意工具都可正確處理", A_en:"Any tool handles them correctly",
            B:"CellPhoneDB 對多亞基複合體有原生支援", B_en:"CellPhoneDB has native support for multi-subunit complexes",
            C:"必須先把細胞合併", C_en:"Cells must be merged first",
            D:"無法分析", D_en:"They cannot be analyzed",
            ans:"B",
            exp:"CellPhoneDB 將多亞基複合體納入資料庫設計，能要求所有亞基同時表達才視為有效互動。",
            exp_en:"CellPhoneDB encodes multi-subunit complexes in its database, requiring all subunits to be expressed for a valid interaction." }
        ],
        "Advanced：軌跡分析 (Trajectory)": [
          { type:"single",
            stem:"Pseudotime 的本質是？",
            stem_en:"What is the nature of pseudotime?",
            A:"絕對時間（小時）", A_en:"Absolute time (hours)",
            B:"以分子相似度排序、推估細胞在動態過程上的相對位置", B_en:"Relative ordering based on molecular similarity to estimate position along a dynamic process",
            C:"細胞數量", C_en:"Cell count",
            D:"批次編號", D_en:"Batch number",
            ans:"B",
            exp:"Pseudotime 來自靜態快照中的表達漸變，非真實實驗時間，是「相對」順序。",
            exp_en:"Pseudotime is derived from expression gradients in a static snapshot — relative order, not real experimental time." },
          { type:"single",
            stem:"下列哪一個工具能藉由 spliced/unspliced mRNA 比例推斷轉變「方向」？",
            stem_en:"Which tool infers transition 'direction' via spliced/unspliced mRNA ratios?",
            A:"Monocle3", A_en:"Monocle3",
            B:"Slingshot", B_en:"Slingshot",
            C:"RNA Velocity (velocyto/scVelo)", C_en:"RNA Velocity (velocyto/scVelo)",
            D:"PAGA", D_en:"PAGA",
            ans:"C",
            exp:"RNA Velocity 基於 unspliced/spliced 比例與動力學模型估算未來狀態方向。",
            exp_en:"RNA Velocity uses unspliced/spliced ratios and dynamics to estimate future state direction." },
          { type:"multi",
            stem:"下列哪些是常見的 trajectory 工具？（多選）",
            stem_en:"Which are common trajectory tools? (Multiple)",
            A:"Monocle3", A_en:"Monocle3",
            B:"Slingshot", B_en:"Slingshot",
            C:"PAGA", C_en:"PAGA",
            D:"DoubletFinder", D_en:"DoubletFinder",
            ans:["A","B","C"],
            exp:"DoubletFinder 與 trajectory 無關。",
            exp_en:"DoubletFinder is unrelated to trajectory." },
          { type:"single",
            stem:"Slingshot 的核心邏輯為？",
            stem_en:"What is Slingshot's core logic?",
            A:"用主曲線（principal curve）擬合分支軌跡", A_en:"Fit principal curves to branched trajectories",
            B:"做 k-means 聚類", B_en:"Run k-means clustering",
            C:"做 PCA", C_en:"Run PCA",
            D:"做 doublet 偵測", D_en:"Run doublet detection",
            ans:"A",
            exp:"Slingshot 在 cluster 之間建立 lineage，再用 simultaneous principal curves 擬合 pseudotime。",
            exp_en:"Slingshot defines lineages between clusters and uses simultaneous principal curves to fit pseudotime." },
          { type:"tf",
            stem:"是非題：Trajectory 分析適用於任何資料，例如純粹的不同器官混合。",
            stem_en:"True/False: Trajectory analysis applies to any data, e.g., pure mixtures of different organs.",
            ans:"F",
            exp:"Trajectory 假設細胞之間存在連續轉變或分化關係；不連續或無生物動態的資料不適用。",
            exp_en:"Trajectory assumes continuous transitions or differentiation between cells; data without dynamics is unsuitable." },
          { type:"single",
            stem:"CytoTRACE 的特色是？",
            stem_en:"What is the feature of CytoTRACE?",
            A:"基於基因多樣性（轉錄組複雜度）推估分化潛能", A_en:"Estimates differentiation potential from gene diversity (transcriptome complexity)",
            B:"做 batch correction", B_en:"Performs batch correction",
            C:"做 doublet 偵測", C_en:"Performs doublet detection",
            D:"取代 PCA", D_en:"Replaces PCA",
            ans:"A",
            exp:"CytoTRACE 觀察未分化細胞通常表達更多種類基因，據此預測分化潛能高低。",
            exp_en:"CytoTRACE leverages the observation that undifferentiated cells express a broader gene set to predict differentiation potential." },
          { type:"single",
            stem:"PAGA 的主要強項是？",
            stem_en:"What is PAGA's main strength?",
            A:"做 marker 視覺化", A_en:"Marker visualization",
            B:"以圖抽象化呈現 cluster 之間的拓撲關係，適合大規模資料", B_en:"Graph-abstracted topology of cluster relationships, suitable for large-scale data",
            C:"做 doublet 偵測", C_en:"Doublet detection",
            D:"取代 normalization", D_en:"Replace normalization",
            ans:"B",
            exp:"PAGA 將每個 cluster 抽象為節點，邊代表轉變強度，便於觀察整體連通與分支。",
            exp_en:"PAGA abstracts each cluster as a node with edges indicating transition strength, useful for global topology and branching." },
          { type:"multi",
            stem:"下列哪些情況適合做 trajectory 分析？（多選）",
            stem_en:"Which scenarios are suitable for trajectory analysis? (Multiple)",
            A:"幹細胞分化過程", A_en:"Stem cell differentiation",
            B:"免疫細胞活化動態", B_en:"Immune cell activation dynamics",
            C:"疾病進程", C_en:"Disease progression",
            D:"純粹獨立器官的混合", D_en:"Pure mixture of independent organs",
            ans:["A","B","C"],
            exp:"D 細胞間無連續轉變關係，trajectory 不適用。",
            exp_en:"D has no continuous transitions; trajectory is not applicable." },
          { type:"tf",
            stem:"是非題：RNA Velocity 與傳統 pseudotime 相比，能提供細胞變化的「方向感」。",
            stem_en:"True/False: RNA Velocity provides a 'sense of direction' for cellular changes, unlike traditional pseudotime.",
            ans:"T",
            exp:"傳統 pseudotime 僅給「順序」，RNA velocity 額外提供未來變化方向。",
            exp_en:"Traditional pseudotime gives only 'order'; RNA velocity additionally provides direction of future change." },
          { type:"single",
            stem:"進行軌跡分析時，下列何者最常被忽略而導致錯誤？",
            stem_en:"Which is the most commonly ignored issue causing trajectory analysis errors?",
            A:"是否事先做 normalization", A_en:"Whether normalization was done first",
            B:"資料是否真的具有連續轉變的生物前提", B_en:"Whether the data truly has biological continuous transitions",
            C:"是否有顏色搭配", C_en:"Whether colors are coordinated",
            D:"檔名是否合規", D_en:"Whether filenames comply",
            ans:"B",
            exp:"Trajectory 對前提假設敏感；強行做沒有動態的資料只會產出無意義「軌跡」。",
            exp_en:"Trajectory is sensitive to assumptions; forcing it on non-dynamic data yields meaningless 'trajectories'." }
        ]
      }
    }
  }
};
